### ISSUE TITLE
[BRANCH:integration-gc] No hardcoded strings

### ISSUE THREAD

**Issue by jbernoudy** [jbernoudy/GitColonyTrial#2]
<a href="https://www.gitcolony.com/redirect//Salesforce/review-branch/890/25056%3F"><img title="GitColony Ant" src="https://www.gitcolony.com/img/ant-comment.png"></a>
Created through GitColony, click [here](https://www.gitcolony.com/redirect//Salesforce/review-branch/890/25056%3F) for details.

**Comment by helenren** [comment]
sure
